name: kajian_fikih
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  google_fonts: ^4.0.4
  email_validator: ^2.1.17
  animated_bottom_navigation_bar: ^1.3.3
  provider: ^6.0.5
  flutter_staggered_grid_view: ^0.7.0
  add_2_calendar: ^3.0.1
  calendar_slider: ^0.0.4
  carousel_slider: ^4.0.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  google_sign_in: ^6.2.1
  animated_snack_bar: ^0.3.1
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  shared_preferences: ^2.1.1

  # firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.2
  cloud_firestore: ^4.13.5
  firebase_storage: ^11.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/main_logo.png
    - assets/main_logo_white.png
    - assets/rounded_polygon.png
    - assets/profile_placeholder.png
    - assets/sharp_polygon.png
    - assets/google_login_button.png
    - assets/dashboard_background.png
    - assets/timer_background.png
    - assets/notifications.png
    - assets/hadist.png
    - assets/quran.png
    - assets/sholat.png
    - assets/silaturahmi.png
    - assets/category_shadow.png
    - assets/explore_on.png
    - assets/explore_off.png
    - assets/home_on.png
    - assets/home_off.png
    - assets/like_on.png
    - assets/like_off.png
    - assets/profile_on.png
    - assets/profile_off.png
    - assets/location_icon.png
    - assets/media_icon.png
    - assets/saved_icon.png
    - assets/privacy_icon.png
    - assets/info_icon.png
    - assets/help_icon.png
    - assets/logout_icon.png
    - assets/like_icon.png
    - assets/liked_icon.png
    - assets/bookmark_icon.png
    - assets/bookmarked_icon.png
    - assets/share_icon.png
    - assets/profile_decoration.png
    - assets/profile_placeholder.png
    - assets/map_placeholder.png
    - assets/edit_profile_icon.png
    - assets/media_placeholder.png
    - assets/offline_event_placeholder.png
    - assets/grid_1.png
    - assets/grid_2.png
    - assets/grid_3.png
    - assets/grid_4.png
